name: Release
on:
  push:
    branches:
      - master

jobs:
test-and-release:
  name: release
  runs-on: ubuntu-18.04
  steps:
    - name: Install yarn
        run: npm install -g yarn
    - name: Install dependencies
        run: yarn
    - name: Release
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
